version: '3.6'

services:
  ## Define FactoryControlApp service
  ia_factoryctrl_app:
    depends_on:
      - ia_common
    build:
      context: $PWD/../FactoryControlApp
      dockerfile: $PWD/../FactoryControlApp/Dockerfile
      args:
        EIS_VERSION: ${EIS_VERSION}
        EIS_UID: ${EIS_UID}
        EIS_USER_NAME: ${EIS_USER_NAME}
    read_only: true
    image: ${DOCKER_REGISTRY}ia_factoryctrl_app:${EIS_VERSION}
    container_name: ia_factoryctrl_app
    hostname: ia_factoryctrl_app
    network_mode: host
    restart: unless-stopped
    environment:
      AppName: "FactoryControlApp"
      DEV_MODE: ${DEV_MODE}

      # MessageBus Endpoint Configuration
      CertType: "zmq"

      # Use IPC mode (zmq_ipc) when VideoIngestion, VideoAnalytics and Visualizer
      # based containers are running on the same host. If they are running on diff
      # host, please use TCP mode for communication.
      # Eg: Stream cfg for
      # IPC: zmq_ipc, <absolute_socket_directory_path>
      # TPC: zmq_tcp, <publisher_host>:<publisher_port>
      SubTopics: "VideoAnalytics/camera1_stream_results"
      camera1_stream_results_cfg : "zmq_tcp,127.0.0.1:65013"
    volumes:
      - "vol_eis_socket:${SOCKET_DIR}"
    user: ${EIS_UID}
    secrets:
      - ca_etcd
      - etcd_FactoryControlApp_cert
      - etcd_FactoryControlApp_key

secrets:
  etcd_FactoryControlApp_cert:
    file: provision/Certificates/FactoryControlApp/FactoryControlApp_client_certificate.pem
  etcd_FactoryControlApp_key:
    file: provision/Certificates/FactoryControlApp/FactoryControlApp_client_key.pem